-- Anka Tasarım · Sipariş Takip — Supabase şeması
-- Supabase › SQL Editor › New query → bu dosyanın tamamını yapıştırın → Run. Bir kez çalıştırılır; tekrar çalıştırmak zararsızdır.

create table if not exists public.customers (
  id integer generated by default as identity primary key,
  ig_user_id text unique,
  ig_username text,
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  address text not null default '',
  city text not null default '',
  district text not null default '',
  postal_code text not null default '',
  notes text not null default '',
  profile_pic text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  order_no integer not null unique,
  customer_id integer not null references public.customers(id),
  status text not null default 'yeni',
  payment_status text not null default 'bekleniyor',
  payment_method text not null default '',
  shipping_payer text not null default 'gonderici',
  lines_json text not null default '[]',
  items text not null default '',
  notes text not null default '',
  labels text not null default '',
  desi double precision,
  package_count integer not null default 1,
  shipping_fee double precision not null default 0,
  subtotal double precision not null default 0,
  total double precision not null default 0,
  source text not null default 'instagram',
  dhl_tracking_no text,
  dhl_shipment_ref text,
  dhl_status text,
  dhl_status_text text,
  dhl_last_check text,
  shipped_at text,
  delivered_at text,
  closed_at text,
  satisfaction text,
  satisfaction_note text,
  satisfaction_asked_at text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  customer_id integer not null references public.customers(id),
  order_id integer references public.orders(id),
  direction text not null,
  channel text not null default 'instagram',
  ig_mid text unique,
  text text not null default '',
  attachments text not null default '[]',
  status text not null default 'ok',
  error text,
  kind text,
  is_read integer not null default 0,
  created_at text not null
);

create table if not exists public.order_events (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete cascade,
  type text not null,
  description text not null default '',
  meta text,
  created_at text not null
);

create table if not exists public.settings (
  key text primary key,
  value text
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_customer on public.orders(customer_id);
create index if not exists idx_messages_customer on public.messages(customer_id, created_at);
create index if not exists idx_messages_order on public.messages(order_id);
create index if not exists idx_events_order on public.order_events(order_id, id);

-- Satır düzeyi güvenlik açık. Uygulama sunucuda çalışır; gizli (service_role) anahtar bu kuralları aşar.
-- Publishable (anon) anahtarla çalıştırmak için aşağıdaki "anka_anon_*" politikaları erişimi açar.
-- Gizli anahtara geçtiğinizde bu politikaları silebilirsiniz: drop policy anka_anon_customers on public.customers; (her tablo için)
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;
alter table public.order_events enable row level security;
alter table public.settings enable row level security;

drop policy if exists anka_anon_customers on public.customers;
drop policy if exists anka_anon_orders on public.orders;
drop policy if exists anka_anon_messages on public.messages;
drop policy if exists anka_anon_order_events on public.order_events;
drop policy if exists anka_anon_settings on public.settings;
create policy anka_anon_customers on public.customers for all to anon using (true) with check (true);
create policy anka_anon_orders on public.orders for all to anon using (true) with check (true);
create policy anka_anon_messages on public.messages for all to anon using (true) with check (true);
create policy anka_anon_order_events on public.order_events for all to anon using (true) with check (true);
create policy anka_anon_settings on public.settings for all to anon using (true) with check (true);

-- Yedek kovasına (yedek) publishable anahtarla dosya yazma/okuma izni
drop policy if exists anka_anon_yedek on storage.objects;
create policy anka_anon_yedek on storage.objects for all to anon using (bucket_id = 'yedek') with check (bucket_id = 'yedek');

-- Yedekten geri yükleme sonrası id sayaçlarını düzeltir (uygulama rpc('reset_sequences') ile çağırır).
create or replace function public.reset_sequences() returns void
language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('public.customers', 'id'), coalesce((select max(id) from public.customers), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.orders', 'id'), coalesce((select max(id) from public.orders), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.messages', 'id'), coalesce((select max(id) from public.messages), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.order_events', 'id'), coalesce((select max(id) from public.order_events), 0) + 1, false);
end $$;
revoke all on function public.reset_sequences() from public, anon, authenticated;

-- Yedek dosyaları için özel Storage kovası (yoksa uygulama da oluşturabilir)
insert into storage.buckets (id, name, public) values ('yedek', 'yedek', false) on conflict (id) do nothing;
